pipeline_name: OCR
text_type: general
use_doc_preprocessor: false
use_textline_orientation: false

engine_config:
  run_mode: paddle

SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv5_mobile_det
    model_dir: /opt/bluetape4k/paddleocr/models/detector
    limit_side_len: 960
    limit_type: max
    max_side_limit: 4000
    thresh: 0.3
    box_thresh: 0.6
    unclip_ratio: 2.0
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv5_mobile_rec
    model_dir: /opt/bluetape4k/paddleocr/models/recognizer
    score_thresh: 0.0
